name: Sync

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          name: devdash-app/devdash

      - name: Unset conflicting git data
        run: git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all

      - name: Push repo state
        run: git push --mirror git@github.com:ewsgit/devdash
