name: Sync

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: clone repo state
        run: git clone --mirror git@github.com/devdash-app/devdash

      - name: list
        run: ls -la

      - name: Push repo state
        run: git push --mirror git@github.com/ewsgit/devdash